  






 /*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/

CREATE TABLE EMAIL (                            
    ID_EMAIL       BIGINT  NOT NULL PRIMARY KEY,

                        
    CX_EMAIL       varchar(120)  NOT NULL,

                        
    FKID_PESSOA       BIGINT  NOT NULL
);

  
CREATE TABLE ENDERECO (                            
    ID_ENDERECO       BIGINT  NOT NULL PRIMARY KEY,

                        
    CEP       varchar(10)  NOT NULL,

                        
    LOGRADOURO       varchar(90)  NOT NULL,

                        
    COMPLEMENTO       varchar(30)  NOT NULL,

                        
    FKID_PESSOA       BIGINT  NOT NULL
);

  
CREATE TABLE PESSOAFISICA (                            
    ID_PESSOA       BIGINT  NOT NULL PRIMARY KEY,

                        
    NOME_COMPLETO       varchar(120)  NOT NULL,

                        
    DT_NASCIMENTO       date  NOT NULL,

                        
    NR_CPF       varchar(11)  NOT NULL
);

  
CREATE TABLE TELEFONECONTATO (                            
    ID_TELEFONE       BIGINT  NOT NULL PRIMARY KEY,

                        
    NR_TELEFONE       varchar(15)  NOT NULL,

                        
    FKID_PESSOA       BIGINT  NOT NULL
);

  

                                                          
CREATE UNIQUE INDEX ON EMAIL (CXEMAIL, FKIDPESSOA);
                                                                                                   
CREATE UNIQUE INDEX ON ENDERECO (CEP, LOGRADOURO, COMPLEMENTO, FKIDPESSOA);
                                                                                                                  
CREATE UNIQUE INDEX ON TELEFONECONTATO (NRTELEFONE, FKIDPESSOA);
 
      
ALTER TABLE EMAIL ADD FOREIGN KEY (FKID_PESSOA) REFERENCES PESSOAFISICA  (ID_PESSOAFISICA)             
ALTER TABLE ENDERECO ADD FOREIGN KEY (FKID_PESSOA) REFERENCES PESSOAFISICA  (ID_PESSOAFISICA)                   
ALTER TABLE TELEFONECONTATO ADD FOREIGN KEY (FKID_PESSOA) REFERENCES PESSOAFISICA  (ID_PESSOAFISICA)   



