







/*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/package br.jus.tse.administrativa;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceException;
import jakarta.persistence.TypedQuery;

@Repository
public class EmailDaoJpa implements EmailDao{

    private EntityManager em;

    private static final Logger LOGGER = LoggerFactory.getLogger(EmailDaoJpa.class);

    public EmailDaoJpa(EntityManager em){
        super();
        this.em = em;
    }

    @Override
    public void save(Email objEmail) {
        try{
            LOGGER.info("Tentando gravar Email: {}", objEmail.logString());
            this.em.persist(objEmail);
            LOGGER.info("Email gravado com sucesso: {}", objEmail.logString());
        }catch (Exception e){
            LOGGER.error("Erro ao gravar Email {}", e.getMessage(), e);
        }
    }

    @Override
    public Optional<Email> findById(Long id) {
        String jpql = "select entidade from Email entidade where entidade.id=:id_entidade";

        TypedQuery<Email>typedObjectQuery = em.createQuery(jpql, Email.class);
        typedObjectQuery.setParameter("id_entidade", id);

        try {
            LOGGER.info("Recuperando Email com ID: {}", id);
            Email objEmail =  typedObjectQuery.getSingleResult();
            LOGGER.info("Email recuperado com sucesso: {}", objEmail.logString());
            return Optional.of(objEmail);
        }
            catch(PersistenceException e) {
            LOGGER.error("Não foi possível recuperar o 'Email' {} =>{}", id, e.getMessage(), e);
        }
        return Optional.empty();
    }

    @Override
    public List<Email> findAll() {
        String jpql = "select entidade from Email entidade";

        TypedQuery<Email>typedObjectQuery = em.createQuery(jpql, Email.class);

        try {
            LOGGER.info("Recuperando a lista de Email.");
            List<Email> list = typedObjectQuery.getResultList();
            LOGGER.info("Tamanho da lista recuperada: {}", list.size());
            return list;
        }
        catch(PersistenceException e) {
            LOGGER.error("Não foi possível recuperar a lista de 'Email' {}.",e.getMessage(), e);
        }
        return Collections.emptyList();
    }

    @Override
    public void update(Email objEmail) {
        try {
            LOGGER.info("Tentando atualizar Email: {}", objEmail.logString());
            em.merge(objEmail);
            LOGGER.info("Email atualizado com sucesso: {}", objEmail.logString());
        }catch(PersistenceException pe) {
            LOGGER.error("Não foi possível atualizar o 'Email' {} => {}.", objEmail, pe.getMessage(), pe);
        }
    }

    @Override
    public void delete(Email objEmail) {
        try{
            LOGGER.info("Tentando excluir Email: {}", objEmail.logString());
            Email objectFinal = em.find(Email.class,  objEmail.getIdEmail() );

            if (objectFinal != null) {
                em.remove(objectFinal);
                LOGGER.info("Email excluída com sucesso: {}", objEmail.logString());
            }
        } catch (Exception e){
            LOGGER.error("Não foi possível excluir 'Email' {} =>{}", objEmail.logString(), e.getMessage(), e);
        }
    }

}