  






 /*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/                                                                                                                                                                                                                          













package br.jus.tse.administrativa;

import java.time.LocalDate;
import java.util.List;
import java.util.ArrayList;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.*;

import br.jus.tse.administrativa.rest.EmailRequest;

@Entity
@Table(name="email", schema="public" )
@SequenceGenerator(name = "sqEmail", sequenceName = "SQ_EMAIL", allocationSize = 1)       
public class Email {
    
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sqEmail")

  
    @Id
    @Column(name="id_email", nullable=false)
    private Long idEmail;    
    @Column(name="cx_email", nullable=false, length=120, unique=true)
    private String cxEmail;

   
 
    @ManyToOne
    @JoinColumn(name="fkid_pessoa", referencedColumnName="id_pessoa")
    private PessoaFisica pessoafisica;



    public Email() {
    }

                                                             
    public Email(Long idEmail, String cxEmail) {
        super();
        
        this.idEmail = idEmail;

        
        this.cxEmail = cxEmail;

            }

                                                                                  
    public Email(Long idEmail, String cxEmail, PessoaFisica pessoafisica) {
        super();
         
        this.idEmail = idEmail;   
        this.cxEmail = cxEmail;    
        this.pessoafisica = pessoafisica;

              }

    public Email(String cxEmail, PessoaFisica pessoafisica) {
        super();
          
        this.pessoafisica = pessoafisica;

        
        this.cxEmail = cxEmail;    
    }


    public void setIdEmail(Long idEmail) {
        this.idEmail = idEmail;
    }
    public Long getIdEmail() {
        return this.idEmail;
    }

 

    public void setCxEmail(String cxEmail) {
        this.cxEmail = cxEmail;
    }
    public String getCxEmail() {
        return this.cxEmail;
    }

 
  


    public PessoaFisica getPessoafisica() {
        return this.pessoafisica;
    }


    public void transform(EmailRequest request){
             this.cxEmail = request.getCxEmail();
           }

    @Override
    public int hashCode(){ return Objects.hash(idEmail, cxEmail); }

    @Override
    public boolean equals (Object obj){
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Email other = (Email) obj;

        return
                  Objects.equals(this.idEmail, other.idEmail) &&          Objects.equals(this.cxEmail, other.cxEmail);
    }

    public String logString() {
        return ("Adicione uma implmenentação adequada.");
    }


}