  






 /*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/
package br.jus.tse.administrativa;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;


@Service
public class EnderecoService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EnderecoService.class);

    private EnderecoDao repository;

    public EnderecoService(EnderecoDao repository) {

        super();
        this.repository = repository;
    }

    @Transactional
    public List<Endereco> findAll() {
        try{
            LOGGER.info("Buscando todos Endereco (service).");
            List<Endereco> list = this.repository.findAll();
            LOGGER.info("Tamanho da lista recuperada (service): {}", list.size());
            return list;
        }catch (Exception e){
            LOGGER.error("Erro ao buscar todos Endereco (service).", e);
            throw e;
        }
    }

    @Transactional
    public Optional<Endereco> findById(Long id) {
        try{
            LOGGER.info("Buscando Endereco com ID (service): {}", id);
            Optional<Endereco> Endereco = this.repository.findById(id);
                if (Endereco.isPresent()) {
                    LOGGER.info("Endereco encontrado (service): {}", Endereco .get().logString());
                } else {
                    LOGGER.warn("Endereco  com ID {} não encontrado (service)", id);
                }
            return Endereco ;
        } catch (Exception e){
            LOGGER.error("Erro ao buscar Endereco com ID (service): {}", id, e);
            throw e;
        }

    }

    @Transactional
    public void save(Endereco Endereco) {
        try {
            LOGGER.info("Criando o Endereco (service): {}", Endereco.logString());
            this.repository.save(Endereco);
            LOGGER.info("Endereco criado com sucesso (service): {}", Endereco.logString());
        } catch (Exception e) {
            LOGGER.error("Erro ao criar Endereco (service): {}", Endereco.logString(), e);
            throw e;
        }
        this.repository.save(Endereco);
    }

    @Transactional
    public void update(Endereco Endereco) {
        try {
            LOGGER.info("Atualizando Endereco (service): {}", Endereco.logString());
            this.repository.update(Endereco);
            LOGGER.info("Endereco atualizado com sucesso (service): {}", Endereco.logString());
        } catch (Exception e) {
            LOGGER.error("Erro ao atualizar Endereco (service): {}", Endereco.logString(), e);
            throw e;
        }
        this.repository.update(Endereco);
    }

    @Transactional
    public void delete(Endereco Endereco) {
        try {
            LOGGER.info("Deletando Endereco (service): {}", Endereco.logString());
            this.repository.delete(Endereco);
            LOGGER.info("Endereco deletado com sucesso (service): {}", Endereco.logString());
        } catch (Exception e) {
            LOGGER.error("Erro ao deletar Endereco (service): {}", Endereco.logString(), e);
            throw e;
        }
        this.repository.delete(Endereco);
    }



}