







/*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/package br.jus.tse.administrativa;

import java.util.List;
import java.util.Optional;

public interface EnderecoDao{

    void save(Endereco Endereco);

    Optional<Endereco>findById(Long id);

    List<Endereco>findAll();

    //obs: entity.name está igual ao nome da classe
    void update(Endereco Endereco);

    void delete(Endereco Endereco);

}