







/*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/package br.jus.tse.administrativa;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceException;
import jakarta.persistence.TypedQuery;

@Repository
public class EnderecoDaoJpa implements EnderecoDao{

    private EntityManager em;

    private static final Logger LOGGER = LoggerFactory.getLogger(EnderecoDaoJpa.class);

    public EnderecoDaoJpa(EntityManager em){
        super();
        this.em = em;
    }

    @Override
    public void save(Endereco objEndereco) {
        try{
            LOGGER.info("Tentando gravar Endereco: {}", objEndereco.logString());
            this.em.persist(objEndereco);
            LOGGER.info("Endereco gravado com sucesso: {}", objEndereco.logString());
        }catch (Exception e){
            LOGGER.error("Erro ao gravar Endereco {}", e.getMessage(), e);
        }
    }

    @Override
    public Optional<Endereco> findById(Long id) {
        String jpql = "select entidade from Endereco entidade where entidade.id=:id_entidade";

        TypedQuery<Endereco>typedObjectQuery = em.createQuery(jpql, Endereco.class);
        typedObjectQuery.setParameter("id_entidade", id);

        try {
            LOGGER.info("Recuperando Endereco com ID: {}", id);
            Endereco objEndereco =  typedObjectQuery.getSingleResult();
            LOGGER.info("Endereco recuperado com sucesso: {}", objEndereco.logString());
            return Optional.of(objEndereco);
        }
            catch(PersistenceException e) {
            LOGGER.error("Não foi possível recuperar o 'Endereco' {} =>{}", id, e.getMessage(), e);
        }
        return Optional.empty();
    }

    @Override
    public List<Endereco> findAll() {
        String jpql = "select entidade from Endereco entidade";

        TypedQuery<Endereco>typedObjectQuery = em.createQuery(jpql, Endereco.class);

        try {
            LOGGER.info("Recuperando a lista de Endereco.");
            List<Endereco> list = typedObjectQuery.getResultList();
            LOGGER.info("Tamanho da lista recuperada: {}", list.size());
            return list;
        }
        catch(PersistenceException e) {
            LOGGER.error("Não foi possível recuperar a lista de 'Endereco' {}.",e.getMessage(), e);
        }
        return Collections.emptyList();
    }

    @Override
    public void update(Endereco objEndereco) {
        try {
            LOGGER.info("Tentando atualizar Endereco: {}", objEndereco.logString());
            em.merge(objEndereco);
            LOGGER.info("Endereco atualizado com sucesso: {}", objEndereco.logString());
        }catch(PersistenceException pe) {
            LOGGER.error("Não foi possível atualizar o 'Endereco' {} => {}.", objEndereco, pe.getMessage(), pe);
        }
    }

    @Override
    public void delete(Endereco objEndereco) {
        try{
            LOGGER.info("Tentando excluir Endereco: {}", objEndereco.logString());
            Endereco objectFinal = em.find(Endereco.class,  objEndereco.getIdEndereco() );

            if (objectFinal != null) {
                em.remove(objectFinal);
                LOGGER.info("Endereco excluída com sucesso: {}", objEndereco.logString());
            }
        } catch (Exception e){
            LOGGER.error("Não foi possível excluir 'Endereco' {} =>{}", objEndereco.logString(), e.getMessage(), e);
        }
    }

}