







/*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/package br.jus.tse.administrativa;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceException;
import jakarta.persistence.TypedQuery;

@Repository
public class PessoaFisicaDaoJpa implements PessoaFisicaDao{

    private EntityManager em;

    private static final Logger LOGGER = LoggerFactory.getLogger(PessoaFisicaDaoJpa.class);

    public PessoaFisicaDaoJpa(EntityManager em){
        super();
        this.em = em;
    }

    @Override
    public void save(PessoaFisica objPessoaFisica) {
        try{
            LOGGER.info("Tentando gravar PessoaFisica: {}", objPessoaFisica.logString());
            this.em.persist(objPessoaFisica);
            LOGGER.info("PessoaFisica gravado com sucesso: {}", objPessoaFisica.logString());
        }catch (Exception e){
            LOGGER.error("Erro ao gravar PessoaFisica {}", e.getMessage(), e);
        }
    }

    @Override
    public Optional<PessoaFisica> findById(Long id) {
        String jpql = "select entidade from PessoaFisica entidade where entidade.id=:id_entidade";

        TypedQuery<PessoaFisica>typedObjectQuery = em.createQuery(jpql, PessoaFisica.class);
        typedObjectQuery.setParameter("id_entidade", id);

        try {
            LOGGER.info("Recuperando PessoaFisica com ID: {}", id);
            PessoaFisica objPessoaFisica =  typedObjectQuery.getSingleResult();
            LOGGER.info("PessoaFisica recuperado com sucesso: {}", objPessoaFisica.logString());
            return Optional.of(objPessoaFisica);
        }
            catch(PersistenceException e) {
            LOGGER.error("Não foi possível recuperar o 'PessoaFisica' {} =>{}", id, e.getMessage(), e);
        }
        return Optional.empty();
    }

    @Override
    public List<PessoaFisica> findAll() {
        String jpql = "select entidade from PessoaFisica entidade";

        TypedQuery<PessoaFisica>typedObjectQuery = em.createQuery(jpql, PessoaFisica.class);

        try {
            LOGGER.info("Recuperando a lista de PessoaFisica.");
            List<PessoaFisica> list = typedObjectQuery.getResultList();
            LOGGER.info("Tamanho da lista recuperada: {}", list.size());
            return list;
        }
        catch(PersistenceException e) {
            LOGGER.error("Não foi possível recuperar a lista de 'PessoaFisica' {}.",e.getMessage(), e);
        }
        return Collections.emptyList();
    }

    @Override
    public void update(PessoaFisica objPessoaFisica) {
        try {
            LOGGER.info("Tentando atualizar PessoaFisica: {}", objPessoaFisica.logString());
            em.merge(objPessoaFisica);
            LOGGER.info("PessoaFisica atualizado com sucesso: {}", objPessoaFisica.logString());
        }catch(PersistenceException pe) {
            LOGGER.error("Não foi possível atualizar o 'PessoaFisica' {} => {}.", objPessoaFisica, pe.getMessage(), pe);
        }
    }

    @Override
    public void delete(PessoaFisica objPessoaFisica) {
        try{
            LOGGER.info("Tentando excluir PessoaFisica: {}", objPessoaFisica.logString());
            PessoaFisica objectFinal = em.find(PessoaFisica.class,  objPessoaFisica.getIdPessoa() );

            if (objectFinal != null) {
                em.remove(objectFinal);
                LOGGER.info("PessoaFisica excluída com sucesso: {}", objPessoaFisica.logString());
            }
        } catch (Exception e){
            LOGGER.error("Não foi possível excluir 'PessoaFisica' {} =>{}", objPessoaFisica.logString(), e.getMessage(), e);
        }
    }

}