







/*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/package br.jus.tse.administrativa;

import java.util.List;
import java.util.Optional;

public interface TelefoneContatoDao{

    void save(TelefoneContato TelefoneContato);

    Optional<TelefoneContato>findById(Long id);

    List<TelefoneContato>findAll();

    //obs: entity.name está igual ao nome da classe
    void update(TelefoneContato TelefoneContato);

    void delete(TelefoneContato TelefoneContato);

}