  






 /*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/ 












package br.jus.tse.administrativa.rest;


import java.time.LocalDate;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.Objects;
          
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import br.jus.tse.administrativa.Endereco;

                         
import br.jus.tse.administrativa.PessoaFisica;


public class EnderecoRequest {

     
    @NotNull(groups = {ValidOnUpdate.class}, message = "idEndereco de Endereco está invalido.")
    @JsonProperty("idEndereco")
    private Long idEndereco;

             @NotNull(groups = {ValidOnCreation.class, ValidOnUpdate.class}, message = "cep de Endereco está invalido.")
    @JsonProperty("cep")
    private String cep;

             @NotNull(groups = {ValidOnCreation.class, ValidOnUpdate.class}, message = "logradouro de Endereco está invalido.")
    @JsonProperty("logradouro")
    private String logradouro;

             @NotNull(groups = {ValidOnCreation.class, ValidOnUpdate.class}, message = "complemento de Endereco está invalido.")
    @JsonProperty("complemento")
    private String complemento;

      
             
    public Endereco transform(PessoaFisica pessoafisica){
        Endereco objEndereco = new Endereco(  this.idEndereco,  this.cep,  this.logradouro,  this.complemento,    pessoafisica);
        return objEndereco;
    }



     
    public void setIdEndereco( Long idEndereco ) {
        this.idEndereco = idEndereco ;
    }
    public Long getIdEndereco() {
        return this.idEndereco;
    }
           
    public void setCep( String cep ) {
        this.cep = cep ;
    }
    public String getCep() {
        return this.cep;
    }

           
    public void setLogradouro( String logradouro ) {
        this.logradouro = logradouro ;
    }
    public String getLogradouro() {
        return this.logradouro;
    }

           
    public void setComplemento( String complemento ) {
        this.complemento = complemento ;
    }
    public String getComplemento() {
        return this.complemento;
    }

        
    @Override
    public String toString() {
        return "EnderecoDTO [                                                                                                                  idEndereco=" + idEndereco + ",   cep=" + cep + ",   logradouro=" + logradouro + ",   complemento=" + complemento + "]";
      }

                                             
    @Override
    public int hashCode(){ return Objects.hash(idEndereco, cep, logradouro, complemento); }

    @Override
    public boolean equals (Object obj){
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EnderecoRequest other = (EnderecoRequest) obj;

        return
                 Objects.equals(this.idEndereco, other.idEndereco) &&          Objects.equals(this.cep, other.cep) &&          Objects.equals(this.logradouro, other.logradouro) &&          Objects.equals(this.complemento, other.complemento);     }

    public Set< String >isValidOnStage (Class<?> stage) {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();


        Set< ConstraintViolation< EnderecoRequest >>violacoes = validator.validate(this, stage);

        if (violacoes.isEmpty()) {
            return Collections.emptySet();
        }

        Set< String > violations = new HashSet<>() ;
        violacoes.forEach((violacao)->{
            violations.add(violacao.getMessageTemplate());
        });

        return violations;
    }

    public String logString() {
        return ("Adicione uma implmenentação adequada.");
    }

}