  






 /*
* Created on 2024-10-30 ( 11:31:29 )
* Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
*/ 












package br.jus.tse.administrativa.rest;


import java.time.LocalDate;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.Objects;
      
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import br.jus.tse.administrativa.TelefoneContato;

                         
import br.jus.tse.administrativa.PessoaFisica;


public class TelefoneContatoRequest {

     
    @NotNull(groups = {ValidOnUpdate.class}, message = "idTelefone de TelefoneContato está invalido.")
    @JsonProperty("idTelefone")
    private Long idTelefone;

             @NotNull(groups = {ValidOnCreation.class, ValidOnUpdate.class}, message = "nrTelefone de TelefoneContato está invalido.")
    @JsonProperty("nrTelefone")
    private String nrTelefone;

      
             
    public TelefoneContato transform(PessoaFisica pessoafisica){
        TelefoneContato objTelefoneContato = new TelefoneContato(  this.idTelefone,  this.nrTelefone,    pessoafisica);
        return objTelefoneContato;
    }



     
    public void setIdTelefone( Long idTelefone ) {
        this.idTelefone = idTelefone ;
    }
    public Long getIdTelefone() {
        return this.idTelefone;
    }
           
    public void setNrTelefone( String nrTelefone ) {
        this.nrTelefone = nrTelefone ;
    }
    public String getNrTelefone() {
        return this.nrTelefone;
    }

        
    @Override
    public String toString() {
        return "TelefoneContatoDTO [                                                              idTelefone=" + idTelefone + ",   nrTelefone=" + nrTelefone + "]";
      }

                           
    @Override
    public int hashCode(){ return Objects.hash(idTelefone, nrTelefone); }

    @Override
    public boolean equals (Object obj){
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TelefoneContatoRequest other = (TelefoneContatoRequest) obj;

        return
                 Objects.equals(this.idTelefone, other.idTelefone) &&          Objects.equals(this.nrTelefone, other.nrTelefone);     }

    public Set< String >isValidOnStage (Class<?> stage) {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();


        Set< ConstraintViolation< TelefoneContatoRequest >>violacoes = validator.validate(this, stage);

        if (violacoes.isEmpty()) {
            return Collections.emptySet();
        }

        Set< String > violations = new HashSet<>() ;
        violacoes.forEach((violacao)->{
            violations.add(violacao.getMessageTemplate());
        });

        return violations;
    }

    public String logString() {
        return ("Adicione uma implmenentação adequada.");
    }

}